name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check, Lint, Unit tests
        run: npm run ci

      - name: Unit test coverage (enforce thresholds)
        env:
          COVERAGE: "1"
          COVERAGE_GLOBAL: "75"
        run: npm test -- --ci

      - name: Build app
        run: npm run build

      - name: Start app (background)
        run: |
          nohup npm run start -- -p 3000 &
          echo $! > .next_pid

      - name: Wait for server
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:3000/api/dashboard > /dev/null; then
              echo "Server is up"; break;
            fi
            echo "Waiting for server... ($i)"; sleep 2;
          done

      - name: Smoke tests
        env:
          BASE_URL: http://localhost:3000
        run: npm run ci:smoke

      - name: Stop app
        if: always()
        run: |
          if [ -f .next_pid ]; then
            kill $(cat .next_pid) || true
          fi
