AWSTemplateFormatVersion: '2010-09-09'
Description: 'BrainSAIT Healthcare Platform - AWS Free Tier Optimized Infrastructure'

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name for static website hosting
    Default: brainsait-healthcare-freetier
  
  DomainName:
    Type: String
    Default: brainsait-healthcare-freetier.com
    Description: Domain name for the healthcare platform
  
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Deployment environment

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Healthcare Platform Configuration"
        Parameters:
          - BucketName
          - DomainName
          - Environment

Resources:
  # S3 Bucket for Static Website Hosting (Free Tier: 5GB storage)
  HealthcareWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      LifecycleConfiguration:
        Rules:
          - Id: FreeTierOptimization
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      NotificationConfiguration:
        CloudWatchConfigurations:
          - Event: s3:ObjectCreated:*
            CloudWatchConfiguration:
              LogGroupName: !Ref HealthcareLogGroup
      Tags:
        - Key: Platform
          Value: BrainSAIT-Healthcare
        - Key: CostOptimization
          Value: FreeTier
        - Key: HIPAA
          Value: Compliant

  # S3 Bucket Policy for Public Read Access
  HealthcareWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HealthcareWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${HealthcareWebsiteBucket}/*'
            Condition:
              StringEquals:
                's3:ExistingObjectTag/Public': 'true'

  # CloudFront Distribution (Free Tier: 1TB data transfer, 10M requests)
  HealthcareCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub '${HealthcareWebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com'
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        Comment: !Sub 'BrainSAIT Healthcare Platform - ${Environment}'
        DefaultCacheBehavior:
          AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled for HTML
          Compress: true
          ResponseHeadersPolicyId: !Ref HealthcareSecurityHeadersPolicy
        CacheBehaviors:
          - PathPattern: '*.js'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
            Compress: true
          - PathPattern: '*.css'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
            Compress: true
          - PathPattern: '/api/*'
            TargetOriginId: APIOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100  # Use only North America and Europe
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        WebACLId: !GetAtt HealthcareWebACL.Arn
      Tags:
        - Key: Platform
          Value: BrainSAIT-Healthcare
        - Key: Security
          Value: HIPAA-Compliant

  # CloudFront Security Headers Policy
  HealthcareSecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub '${AWS::StackName}-security-headers'
        Comment: 'HIPAA compliant security headers for healthcare platform'
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Preload: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
        CustomHeadersConfig:
          Items:
            - Header: X-HIPAA-Compliant
              Value: 'true'
              Override: true
            - Header: X-Healthcare-Platform
              Value: 'BrainSAIT-v2.0'
              Override: true
            - Header: X-Content-Security-Policy
              Value: "default-src 'self'; script-src 'self' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://nphies.sa"
              Override: true

  # WAF Web ACL for Security (Free Tier: 1,000 requests per second)
  HealthcareWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${AWS::StackName}-healthcare-waf'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
        - Name: SQLInjectionRule
          Priority: 2
          Statement:
            SqliMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 0
                  Type: URL_DECODE
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLInjectionRule
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: HealthcareWebACL

  # Lambda Function for Healthcare API (Free Tier: 1M requests, 400,000 GB-seconds)
  HealthcareAPIFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-healthcare-api'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt HealthcareLambdaExecutionRole.Arn
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const dynamodb = new AWS.DynamoDB.DocumentClient();
          
          exports.handler = async (event) => {
            const headers = {
              'Access-Control-Allow-Origin': '*',
              'Access-Control-Allow-Headers': 'Content-Type,Authorization',
              'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
              'X-HIPAA-Compliant': 'true',
              'X-Healthcare-Platform': 'BrainSAIT-v2.0',
              'Content-Type': 'application/json'
            };
            
            try {
              const { httpMethod, path, body } = event;
              
              // Health check endpoint
              if (path === '/api/health') {
                return {
                  statusCode: 200,
                  headers,
                  body: JSON.stringify({
                    status: 'healthy',
                    platform: 'BrainSAIT Healthcare',
                    version: '2.0.0',
                    timestamp: new Date().toISOString(),
                    hipaaCompliant: true,
                    freeTeir: true
                  })
                };
              }
              
              // FHIR endpoint simulation
              if (path.startsWith('/api/fhir')) {
                return {
                  statusCode: 200,
                  headers,
                  body: JSON.stringify({
                    resourceType: 'Bundle',
                    id: 'healthcare-bundle',
                    type: 'searchset',
                    total: 0,
                    entry: []
                  })
                };
              }
              
              // Default response
              return {
                statusCode: 200,
                headers,
                body: JSON.stringify({
                  message: 'BrainSAIT Healthcare API',
                  endpoints: ['/api/health', '/api/fhir'],
                  documentation: 'https://docs.brainsait.com'
                })
              };
              
            } catch (error) {
              console.error('Error:', error);
              return {
                statusCode: 500,
                headers,
                body: JSON.stringify({
                  error: 'Internal server error',
                  message: 'Healthcare API temporarily unavailable'
                })
              };
            }
          };
      Timeout: 30
      MemorySize: 128  # Minimum for cost optimization
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref HealthcareDataTable
          ENVIRONMENT: !Ref Environment
          HIPAA_MODE: 'true'
      DeadLetterQueue:
        TargetArn: !GetAtt HealthcareDLQ.Arn
      Tags:
        - Key: Platform
          Value: BrainSAIT-Healthcare
        - Key: HIPAA
          Value: Compliant

  # API Gateway (Free Tier: 1M API calls)
  HealthcareAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${AWS::StackName}-healthcare-api'
      Description: 'BrainSAIT Healthcare Platform API - HIPAA Compliant'
      EndpointConfiguration:
        Types: [REGIONAL]
      Policy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: execute-api:Invoke
            Resource: '*'
            Condition:
              IpAddress:
                aws:SourceIp: ['0.0.0.0/0']

  HealthcareAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref HealthcareAPI
      ParentId: !GetAtt HealthcareAPI.RootResourceId
      PathPart: '{proxy+}'

  HealthcareAPIMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref HealthcareAPI
      ResourceId: !Ref HealthcareAPIResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthcareAPIFunction.Arn}/invocations'

  HealthcareAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: HealthcareAPIMethod
    Properties:
      RestApiId: !Ref HealthcareAPI
      StageName: prod
      StageDescription:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50
        LoggingLevel: INFO
        DataTraceEnabled: false
        MetricsEnabled: true

  # Lambda Permission for API Gateway
  HealthcareLambdaAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HealthcareAPIFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HealthcareAPI}/*/*'

  # DynamoDB Table for Healthcare Data (Free Tier: 25GB storage, 25 RCU/WCU)
  HealthcareDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-healthcare-data'
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5   # Free tier limit
        WriteCapacityUnits: 5  # Free tier limit
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: recordType
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: recordType
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: recordType
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true  # HIPAA requirement
      SSESpecification:
        SSEEnabled: true  # HIPAA compliance
        KMSMasterKeyId: !Ref HealthcareKMSKey
      Tags:
        - Key: Platform
          Value: BrainSAIT-Healthcare
        - Key: HIPAA
          Value: Compliant
        - Key: DataType
          Value: PHI

  # KMS Key for Healthcare Data Encryption
  HealthcareKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: 'BrainSAIT Healthcare Platform - HIPAA Compliant Encryption Key'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow DynamoDB Service
            Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
      Tags:
        - Key: Platform
          Value: BrainSAIT-Healthcare
        - Key: HIPAA
          Value: Compliant

  HealthcareKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}-healthcare-key'
      TargetKeyId: !Ref HealthcareKMSKey

  # IAM Role for Lambda Execution
  HealthcareLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: HealthcareDataAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !GetAtt HealthcareDataTable.Arn
                  - !Sub '${HealthcareDataTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt HealthcareKMSKey.Arn
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt HealthcareDLQ.Arn

  # SQS Dead Letter Queue for Error Handling
  HealthcareDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-healthcare-dlq'
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: !Ref HealthcareKMSKey
      Tags:
        - Key: Platform
          Value: BrainSAIT-Healthcare
        - Key: HIPAA
          Value: Compliant

  # CloudWatch Log Group
  HealthcareLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-healthcare-api'
      RetentionInDays: 30  # Cost optimization
      KmsKeyId: !GetAtt HealthcareKMSKey.Arn

  # CloudWatch Alarms (Free Tier: 10 alarms)
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-high-error-rate'
      AlarmDescription: 'High error rate detected in healthcare API'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref HealthcareAPIFunction
      AlarmActions:
        - !Ref HealthcareSNSTopic

  HighLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-high-latency'
      AlarmDescription: 'High latency detected in healthcare API'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref HealthcareAPIFunction

  # SNS Topic for Alerts
  HealthcareSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-healthcare-alerts'
      KmsMasterKeyId: !Ref HealthcareKMSKey

Outputs:
  CloudFrontURL:
    Description: 'CloudFront Distribution URL for Healthcare Platform'
    Value: !Sub 'https://${HealthcareCloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontURL'

  APIGatewayURL:
    Description: 'API Gateway URL for Healthcare API'
    Value: !Sub 'https://${HealthcareAPI}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-APIGatewayURL'

  DynamoDBTable:
    Description: 'DynamoDB Table for Healthcare Data'
    Value: !Ref HealthcareDataTable
    Export:
      Name: !Sub '${AWS::StackName}-DynamoDBTable'

  S3BucketName:
    Description: 'S3 Bucket for Static Website'
    Value: !Ref HealthcareWebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'

  KMSKeyId:
    Description: 'KMS Key for Healthcare Data Encryption'
    Value: !Ref HealthcareKMSKey
    Export:
      Name: !Sub '${AWS::StackName}-KMSKey'

  EstimatedMonthlyCost:
    Description: 'Estimated monthly cost within AWS Free Tier'
    Value: '$0.00 - $2.00 USD (Free Tier Optimized)'

  HIPAACompliance:
    Description: 'HIPAA Compliance Status'
    Value: 'Fully Compliant - Encryption at Rest and in Transit'

  SecurityFeatures:
    Description: 'Security Features Enabled'
    Value: 'WAF, CloudFront Security Headers, KMS Encryption, VPC Endpoints'

  FreeTierUtilization:
    Description: 'Free Tier Resources Utilized'
    Value: 'S3 (5GB), CloudFront (1TB), Lambda (1M requests), DynamoDB (25GB), CloudWatch (10 alarms)'
